data:
  dataset: gowalla
evaluation:
  k: 20
  metrics:
  - recall@20
  - ndcg@20
model:
  emb_dim: 64
  n_layers: 3
training:
  batch_size: 1024
  checkpoint_dir: models/lightgcn/outputs/checkpoints
  device: cuda
  epochs: 50
  lr: 0.001
  save_every_n_epochs: 50
  shuffle: true
  weight_decay: 0.0001
